### ISSUE TITLE
Container won't start using the "Run CDOGS in unauthenticated mode" method in the Quick Start README section

### ISSUE THREAD

**Issue by houldsg** [bcgov/common-document-generation-service#75]
#### Describe the bug
The container won't start using the "Run CDOGS in unauthenticated mode" command in the quick start example ```docker run -it --rm -p 3000:3000 bcgovimages/common-document-generation-service:latest```

#### To Reproduce

1. From a machine with docker installed, run ```docker run -it --rm -p 3000:3000 bcgovimages/common-document-generation-service:latest```
2. See error `Error: Configuration property \"keycloak.clientId\" is not defined`

```js
{"date":"Fri Oct 15 2021 14:07:22 GMT+0000 (Coordinated Universal Time)","error":{},"exception":true,"level":"error","message":"uncaughtException: Configuration property \"keycloak.clientId\" is not defined\nError: Configuration property \"keycloak.clientId\" is not defined\n    at Config.get (/opt/app-root/src/node_modules/config/lib/config.js:182:11)\n    at Object.<anonymous> (/opt/app-root/src/src/routes/v1/index.js:11:25)\n    at Module._compile (internal/modules/cjs/loader.js:1072:14)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)\n    at Module.load (internal/modules/cjs/loader.js:937:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:778:12)\n    at Module.require (internal/modules/cjs/loader.js:961:19)\n    at require (internal/modules/cjs/helpers.js:92:18)\n    at Object.<anonymous> (/opt/app-root/src/app.js:12:18)\n    at Module._compile (internal/modules/cjs/loader.js:1072:14)","os":{"loadavg":[3.35,3.42,3.43],"uptime":92464.42},"process":{"argv":["/usr/local/bin/node","/opt/app-root/src/bin/www"],"cwd":"/opt/app-root/src","execPath":"/usr/local/bin/node","gid":0,"memoryUsage":{"arrayBuffers":453676,"external":2001333,"heapTotal":34873344,"heapUsed":14646576,"rss":64163840},"pid":66,"uid":0,"version":"v14.17.5"},"stack":"Error: Configuration property \"keycloak.clientId\" is not defined\n    at Config.get (/opt/app-root/src/node_modules/config/lib/config.js:182:11)\n    at Object.<anonymous> (/opt/app-root/src/src/routes/v1/index.js:11:25)\n    at Module._compile (internal/modules/cjs/loader.js:1072:14)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)\n    at Module.load (internal/modules/cjs/loader.js:937:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:778:12)\n    at Module.require (internal/modules/cjs/loader.js:961:19)\n    at require (internal/modules/cjs/helpers.js:92:18)\n    at Object.<anonymous> (/opt/app-root/src/app.js:12:18)\n    at Module._compile (internal/modules/cjs/loader.js:1072:14)","timestamp":"2021-10-15T14:07:22.912Z","trace":[{"column":11,"file":"/opt/app-root/src/node_modules/config/lib/config.js","function":"Config.get","line":182,"method":"get","native":false},{"column":25,"file":"/opt/app-root/src/src/routes/v1/index.js","function":null,"line":11,"method":null,"native":false},{"column":14,"file":"internal/modules/cjs/loader.js","function":"Module._compile","line":1072,"method":"_compile","native":false},{"column":10,"file":"internal/modules/cjs/loader.js","function":"Module._extensions..js","line":1101,"method":".js","native":false},{"column":32,"file":"internal/modules/cjs/loader.js","function":"Module.load","line":937,"method":"load","native":false},{"column":12,"file":"internal/modules/cjs/loader.js","function":"Module._load","line":778,"method":"_load","native":false},{"column":19,"file":"internal/modules/cjs/loader.js","function":"Module.require","line":961,"method":"require","native":false},{"column":18,"file":"internal/modules/cjs/helpers.js","function":"require","line":92,"method":null,"native":false},{"column":18,"file":"/opt/app-root/src/app.js","function":null,"line":12,"method":null,"native":false},{"column":14,"file":"internal/modules/cjs/loader.js","function":"Module._compile","line":1072,"method":"_compile","native":false}]}
```
#### Expected behavior
The service starts

#### Desktop (please complete the following information):
- OS: docker running on WSL2 (Windows 10 host)
- Version: https://hub.docker.com/layers/bcgovimages/common-document-generation-service/latest/images/sha256-bbc64983f5ccfb8110fe00a8ee4f5458650e0252b8041d355bca21cacfe1d88f?context=explore

#### Additional context
Since the error stems from undefined variables, I supplied empty KC_CLIENTID and KC_CLIENTSECRET vairables and it runs successfully. It looks like the "config" library throws an error if you try to `get` anything that wasn't supplied in any of the config sources.
`docker run -it --rm -p 9000:3000 -e KC_CLIENTID= -e KC_CLIENTSECRET= bcgovimages/common-document-generation-service:latest`

**Comment by jujaga** [comment]
Hi thanks for the report. This should be fixed in the upcoming 2.4.0 release.
